# Servo Config for Sheldon
#

dynamixels: [

  'head_sidetilt_joint', 'head_tilt_joint', 'head_pan_joint',

  'right_arm_shoulder_rotate_joint', 'right_arm_shoulder_lift_joint', 
  'right_arm_elbow_rotate_joint',    'right_arm_elbow_bend_joint',
  'right_arm_wrist_rotate_joint',    'right_arm_gripper_finger_joint', 

  'left_arm_shoulder_rotate_joint',  'left_arm_shoulder_lift_joint',
  'left_arm_elbow_rotate_joint',     'left_arm_elbow_bend_joint', 
  'left_arm_wrist_rotate_joint',     'left_arm_gripper_finger_joint']


controllers: [

  'head_sidetilt_joint', 'head_tilt_joint', 'head_pan_joint',

  'right_arm_shoulder_rotate_joint', 'right_arm_shoulder_lift_joint', 
  'right_arm_elbow_rotate_joint',    'right_arm_elbow_bend_joint',
  'right_arm_wrist_rotate_joint',    'right_arm_gripper_finger_joint', 

  'left_arm_shoulder_rotate_joint',  'left_arm_shoulder_lift_joint',
  'left_arm_elbow_rotate_joint',     'left_arm_elbow_bend_joint', 
  'left_arm_wrist_rotate_joint',     'left_arm_gripper_finger_joint']



head_sidetilt_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head_sidetilt_joint
    joint_speed: 0.5
    motor:
        id: 2
        init: 2047 
        min: 0     # sidetilt left
        max: 4095  # sidetilt right

head_tilt_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head_tilt_joint
    joint_speed: 0.25
    motor:
        id: 3
        init: 2047
        min: 0     # look up
        max: 4095  # look down

head_pan_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head_pan_joint
    joint_speed: 0.5
    motor:
        id: 4
        init: 2047
        min: 0     # look right
        max: 4095  # look left

right_arm_shoulder_rotate_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_arm_shoulder_rotate_joint
    joint_speed: 1.0
    motor:
        id: 16
        init: 2047
        min: 0
        max: 4095

right_arm_shoulder_lift_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_arm_shoulder_lift_joint
    joint_speed: 0.25
    motor:
        id: 6
        init: 2047
        min: 0
        max: 4095

right_arm_elbow_rotate_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_arm_elbow_rotate_joint
    joint_speed: 1.0
    motor:
        id: 7
        init: 2047
        min: 0
        max: 4095

right_arm_elbow_bend_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_arm_elbow_bend_joint
    joint_speed: 1.0
    motor:
        id: 8
        init: 2047
        min: 0
        max: 4095

right_arm_wrist_rotate_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_arm_wrist_rotate_joint
    joint_speed: 1.0
    motor:
        id: 9
        init: 2047
        min: 0
        max: 4095

right_arm_gripper_finger_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_arm_gripper_finger_joint
    joint_speed: 1.0
    motor:
        id: 10
        init: 2047
        min: 0
        max: 4095


left_arm_shoulder_rotate_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_arm_shoulder_rotate_joint
    joint_speed: 1.0
    motor:
        id: 17
        init: 2047
        min: 0
        max: 4095

left_arm_shoulder_lift_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_arm_shoulder_lift_joint
    joint_speed: 0.25
    motor:
        id: 11
        init: 2047
        min: 0
        max: 4095

left_arm_elbow_rotate_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_arm_elbow_rotate_joint
    joint_speed: 1.0
    motor:
        id: 12
        init: 2047
        min: 0
        max: 4095

left_arm_elbow_bend_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_arm_elbow_bend_joint
    joint_speed: 1.0
    motor:
        id: 13
        init: 2047
        min: 0
        max: 4095

left_arm_wrist_rotate_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_arm_wrist_rotate_joint
    joint_speed: 1.0
    motor:
        id: 14
        init: 2047
        min: 0
        max: 4095

left_arm_gripper_finger_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_arm_gripper_finger_joint
    joint_speed: 1.0
    motor:
        id: 15
        init: 2047
        min: 4095
        max: 0


