controller_list:
  - name: fake_right_arm_controller
    joints:
      - right_arm_shoulder_rotate_joint
      - right_arm_shoulder_lift_joint
      - right_arm_elbow_rotate_joint
      - right_arm_elbow_bend_joint
      - right_arm_wrist_rotate_joint
  - name: fake_left_arm_controller
    joints:
      - left_arm_shoulder_rotate_joint
      - left_arm_shoulder_lift_joint
      - left_arm_elbow_rotate_joint
      - left_arm_elbow_bend_joint
      - left_arm_wrist_rotate_joint
  - name: fake_right_gripper_controller
    joints:
      - right_arm_gripper_finger_joint
  - name: fake_left_gripper_controller
    joints:
      - left_arm_gripper_finger_joint